export const DEFAULT_COLORS = [
  {
    category: 'black',
    key: '#000000',
    english: ['black'],
    chinese: ['黑色', '墨黑色'],
  },
  {
    category: 'silver',
    key: '#c0c0c0',
    english: ['silver'],
    chinese: ['银色', '银灰色'],
  },
  {
    category: 'gray',
    key: '#808080',
    english: ['gray'],
    chinese: ['灰色', '灰暗色'],
  },
  {
    category: 'white',
    key: '#ffffff',
    english: ['white'],
    chinese: ['白色', '纯白色'],
  },
  {
    category: 'brown',
    key: '#800000',
    english: ['maroon', 'brown'],
    chinese: ['栗红色', '褐红色', '栗色', '褐色'],
  },
  {
    category: 'red',
    key: '#ff0000',
    english: ['red', 'crimson'],
    chinese: ['红色', '猩红色', '朱红色', '深红色'],
  },
  {
    category: 'purple',
    key: '#800080',
    english: ['purple'],
    chinese: ['紫色', '深紫色'],
  },
  {
    category: 'purple',
    key: '#ff00ff',
    english: ['fuchsia', 'magenta'],
    chinese: ['紫红色', '洋红色', '粉紫色', '洋红色'],
  },
  {
    category: 'green',
    key: '#008000',
    english: ['green', 'lime'],
    chinese: ['绿色', '鲜绿色', '草绿色'],
  },
  {
    category: 'green',
    key: '#00ff00',
    english: ['lime', 'green'],
    chinese: ['鲜绿色', '绿色', '草绿色'],
  },
  {
    category: 'green',
    key: '#808000',
    english: ['olive', 'green'],
    chinese: ['橄榄色', '橄榄绿色', '自然橄榄色', '绿色'],
  },
  {
    category: 'yellow',
    key: '#ffff00',
    english: ['yellow'],
    chinese: ['黄色', '明黄色', '金黄色'],
  },
  {
    category: 'blue',
    key: '#000080',
    english: ['navy', 'blue'],
    chinese: ['深蓝色', '海军蓝色', '深夜蓝色', '蓝色', '湛蓝色', '宝蓝色'],
  },
  {
    category: 'blue',
    key: '#0000ff',
    english: ['blue'],
    chinese: ['蓝色', '湛蓝色', '宝蓝色'],
  },
  {
    category: 'green',
    key: '#008080',
    english: ['teal', 'green'],
    chinese: ['蓝绿色', '湖绿色', '蓝翠绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#00ffff',
    english: ['aqua', 'cyan', 'blue', 'green'],
    chinese: ['青色', '蓝绿色', '湖绿色', '蓝色', '湛蓝色', '绿色'],
  },
  {
    category: 'blue',
    key: '#f0f8ff',
    english: ['aliceblue', 'blue'],
    chinese: ['艾莉丝蓝', '淡蓝色', '蓝色', '湛蓝色', '宝蓝色'],
  },
  {
    category: 'white',
    key: '#faebd7',
    english: ['antiquewhite', 'white'],
    chinese: ['古董白色', '米白色', '白色'],
  },
  {
    category: 'green',
    key: '#7fffd4',
    english: ['aquamarine', 'green'],
    chinese: ['碧绿色', '绿松石色', '绿色'],
  },
  {
    category: 'blue',
    key: '#f0ffff',
    english: ['azure', 'cyan', 'blue'],
    chinese: ['天蓝色', '湛蓝色', '宝蓝色', '青色'],
  },
  {
    category: 'yellow',
    key: '#f5f5dc',
    english: ['beige', 'yellow'],
    chinese: ['米色', '米白色', '黄色'],
  },
  {
    category: 'orange',
    key: '#ffe4c4',
    english: ['bisque', 'orange'],
    chinese: ['桔黄色', '橙黄色', '橙色', '黄色'],
  },
  {
    category: 'yellow',
    key: '#ffebcd',
    english: ['blanchedalmond', 'beige', 'yellow'],
    chinese: ['杏仁白', '淡米色', '米白色', '黄色'],
  },
  {
    category: 'purple',
    key: '#8a2be2',
    english: ['blueviolet', 'purple'],
    chinese: ['蓝紫色', '紫色', '深紫色'],
  },
  {
    category: 'brown',
    key: '#a52a2a',
    english: ['brown'],
    chinese: ['褐色', '棕色'],
  },
  {
    category: 'brown',
    key: '#deb887',
    english: ['burlywood', 'brown'],
    chinese: ['实木色', '褐色', '棕色'],
  },
  {
    category: 'blue',
    key: '#5f9ea0',
    english: ['cadetblue', 'blue'],
    chinese: ['军服蓝', '湛蓝色', '宝蓝色'],
  },
  {
    category: 'green',
    key: '#7fff00',
    english: ['chartreuse', 'green', 'yellow'],
    chinese: ['黄绿色', '草绿色', '绿色', '黄色'],
  },
  {
    category: 'brown',
    key: '#d2691e',
    english: ['chocolate', 'brown'],
    chinese: ['巧克力色', '褐色', '棕色'],
  },
  {
    category: 'orange',
    key: '#ff7f50',
    english: ['coral', 'orange'],
    chinese: ['珊瑚色', '橙色', '桔红色'],
  },
  {
    category: 'blue',
    key: '#6495ed',
    english: ['cornflowerblue', 'blue'],
    chinese: ['矢车菊蓝色', '湛蓝色', '宝蓝色', '蓝色'],
  },
  {
    category: 'yellow',
    key: '#fff8dc',
    english: ['cornsilk', 'beige', 'yellow'],
    chinese: ['米黄色', '淡米色', '米白色', '黄色'],
  },
  {
    category: 'red',
    key: '#dc143c',
    english: ['crimson', 'red'],
    chinese: ['绯红色', '深红色', '红色'],
  },
  {
    category: 'blue',
    key: '#00008b',
    english: ['darkblue', 'blue'],
    chinese: ['深蓝色', '湛蓝色', '宝蓝色', '蓝色'],
  },
  {
    category: 'cyan',
    key: '#008b8b',
    english: ['darkcyan', 'cyan', 'blue', 'green'],
    chinese: ['深青色', '青色', '蓝色', '绿色'],
  },
  {
    category: 'yellow',
    key: '#b8860b',
    english: ['darkgoldenrod', 'yellow'],
    chinese: ['深金黄色', '金黄色', '黄色'],
  },
  {
    category: 'gray',
    key: '#a9a9a9',
    english: ['darkgray', 'grey'],
    chinese: ['深灰色', '灰色'],
  },
  {
    category: 'green',
    key: '#006400',
    english: ['darkgreen', 'green'],
    chinese: ['深绿色', '绿色'],
  },
  {
    category: 'yellow',
    key: '#bdb76b',
    english: ['darkkhaki', 'yellow'],
    chinese: ['深卡其色', '卡其色', '黄色'],
  },
  {
    category: 'purple',
    key: '#8b008b',
    english: ['darkmagenta', 'purple'],
    chinese: ['深品红色', '品红色', '紫色'],
  },
  {
    category: 'green',
    key: '#556b2f',
    english: ['darkolivegreen', 'olive', 'green'],
    chinese: ['深橄榄绿色', '橄榄绿色', '绿色'],
  },
  {
    category: 'orange',
    key: '#ff8c00',
    english: ['darkorange', 'orange'],
    chinese: ['深橙色', '橙色'],
  },
  {
    category: 'purple',
    key: '#9932cc',
    english: ['darkorchid', 'purple'],
    chinese: ['深兰花紫', '兰花紫', '紫色'],
  },
  {
    category: 'red',
    key: '#8b0000',
    english: ['darkred', 'red'],
    chinese: ['深红色', '红色'],
  },
  {
    category: 'orange',
    key: '#e9967a',
    english: ['darksalmon', 'orange'],
    chinese: ['深橙红色', '橙红色', '橙色'],
  },
  {
    category: 'green',
    key: '#8fbc8f',
    english: ['darkseagreen', 'green'],
    chinese: ['深海蓝绿色', '海蓝绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#483d8b',
    english: ['darkslateblue', 'blue'],
    chinese: ['深岩蓝色', '岩蓝色', '蓝色'],
  },
  {
    category: 'gray',
    key: '#2f4f4f',
    english: ['darkslategray', 'darkslategrey', 'grey'],
    chinese: ['深岩灰色', '岩灰色', '灰色'],
  },
  {
    category: 'cyan',
    key: '#00ced1',
    english: ['darkturquoise', 'cyan', 'blue', 'green'],
    chinese: ['深青绿色', '青绿色', '蓝色', '绿色'],
  },
  {
    category: 'purple',
    key: '#9400d3',
    english: ['darkviolet', 'purple'],
    chinese: ['深紫罗兰色', '紫罗兰色', '紫色'],
  },
  {
    category: 'pink',
    key: '#ff1493',
    english: ['deeppink', 'red', 'pink'],
    chinese: ['深粉红色', '粉红色', '红色', '粉色'],
  },
  {
    category: 'blue',
    key: '#00bfff',
    english: ['deepskyblue', 'blue'],
    chinese: ['深天蓝色', '天蓝色', '蓝色'],
  },
  {
    category: 'gray',
    key: '#696969',
    english: ['dimgray', 'dimgrey', 'grey'],
    chinese: ['深灰色', '灰色'],
  },
  {
    category: 'blue',
    key: '#1e90ff',
    english: ['dodgerblue', 'blue'],
    chinese: ['道奇蓝色', '蓝色'],
  },
  {
    category: 'red',
    key: '#b22222',
    english: ['firebrick', 'red'],
    chinese: ['火砖红色', '红色'],
  },
  {
    category: 'white',
    key: '#fffaf0',
    english: ['floralwhite', 'white'],
    chinese: ['花卉白色', '白色'],
  },
  {
    category: 'green',
    key: '#228b22',
    english: ['forestgreen', 'green'],
    chinese: ['森林绿色', '绿色'],
  },
  {
    category: 'gray',
    key: '#dcdcdc',
    english: ['gainsboro', 'grey'],
    chinese: ['淡灰色', '灰色'],
  },
  {
    category: 'white',
    key: '#f8f8ff',
    english: ['ghostwhite', 'white'],
    chinese: ['幽灵白色', '白色'],
  },
  {
    category: 'yellow',
    key: '#ffd700',
    english: ['gold', 'yellow'],
    chinese: ['金色', '黄色'],
  },
  {
    category: 'yellow',
    key: '#daa520',
    english: ['goldenrod', 'yellow'],
    chinese: ['金麒麟色', '黄色'],
  },
  {
    category: 'yellow',
    key: '#adff2f',
    english: ['greenyellow', 'yellow'],
    chinese: ['绿黄色', '黄色'],
  },
  {
    category: 'white',
    key: '#f0fff0',
    english: ['honeydew', 'white'],
    chinese: ['蜜露白色', '白色'],
  },
  {
    category: 'pink',
    key: '#ff69b4',
    english: ['hotpink', 'pink'],
    chinese: ['热粉红', '粉色'],
  },
  {
    category: 'red',
    key: '#cd5c5c',
    english: ['indianred', 'red'],
    chinese: ['印度红', '红色'],
  },
  {
    category: 'purple',
    key: '#4b0082',
    english: ['indigo', 'purple'],
    chinese: ['靛青色', '紫色'],
  },
  {
    category: 'white',
    key: '#fffff0',
    english: ['ivory', 'white'],
    chinese: ['象牙白色', '白色'],
  },
  {
    category: 'yellow',
    key: '#f0e68c',
    english: ['khaki', 'yellow'],
    chinese: ['黄褐色', '黄色'],
  },
  {
    category: 'purple',
    key: '#e6e6fa',
    english: ['lavender', 'purple'],
    chinese: ['淡紫色', '紫色'],
  },
  {
    category: 'red',
    key: '#fff0f5',
    english: ['lavenderblush', 'red'],
    chinese: ['淡紫红', '红色'],
  },
  {
    category: 'green',
    key: '#7cfc00',
    english: ['lawngreen', 'green'],
    chinese: ['草坪绿色', '绿色'],
  },
  {
    category: 'yellow',
    key: '#fffacd',
    english: ['lemonchiffon', 'yellow'],
    chinese: ['柠檬雪纺色', '黄色'],
  },
  {
    category: 'blue',
    key: '#add8e6',
    english: ['lightblue', 'blue'],
    chinese: ['淡蓝色', '蓝色'],
  },
  {
    category: 'pink',
    key: '#f08080',
    english: ['lightcoral', 'pink', 'red'],
    chinese: ['淡珊瑚红色', '淡粉红', '粉色'],
  },
  {
    category: 'blue',
    key: '#e0ffff',
    english: ['lightcyan', 'blue'],
    chinese: ['淡青色', '蓝色'],
  },
  {
    category: 'yellow',
    key: '#fafad2',
    english: ['lightgoldenrodyellow', 'yellow'],
    chinese: ['淡金黄色', '黄色'],
  },
  {
    category: 'gray',
    key: '#d3d3d3',
    english: ['lightgray', 'grey'],
    chinese: ['淡灰色', '灰色'],
  },
  {
    category: 'green',
    key: '#90ee90',
    english: ['lightgreen', 'green'],
    chinese: ['淡绿色', '绿色'],
  },
  {
    category: 'gray',
    key: '#d3d3d3',
    english: ['lightgrey', 'grey'],
    chinese: ['淡灰色', '灰色'],
  },
  {
    category: 'pink',
    key: '#ffb6c1',
    english: ['lightpink', 'pink', 'red'],
    chinese: ['淡粉红色', '粉红色', '粉色'],
  },
  {
    category: 'pink',
    key: '#ffa07a',
    english: ['lightsalmon', 'pink', 'red'],
    chinese: ['淡鲑红色', '淡粉红色', '粉色'],
  },
  {
    category: 'green',
    key: '#20b2aa',
    english: ['lightseagreen', 'green'],
    chinese: ['淡海绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#87cefa',
    english: ['lightskyblue', 'blue'],
    chinese: ['淡天蓝色', '蓝色'],
  },
  {
    category: 'gray',
    key: '#778899',
    english: ['lightslategray', 'grey'],
    chinese: ['淡蓝灰色', '灰色'],
  },
  {
    category: 'gray',
    key: '#778899',
    english: ['lightslategrey', 'grey'],
    chinese: ['淡蓝灰色', '灰色'],
  },
  {
    category: 'blue',
    key: '#b0c4de',
    english: ['lightsteelblue', 'blue'],
    chinese: ['淡钢蓝色', '蓝色'],
  },
  {
    category: 'yellow',
    key: '#ffffe0',
    english: ['lightyellow', 'yellow'],
    chinese: ['淡黄色', '黄色'],
  },
  {
    category: 'green',
    key: '#32cd32',
    english: ['limegreen', 'green'],
    chinese: ['青柠绿色', '绿色'],
  },
  {
    category: 'white',
    key: '#faf0e6',
    english: ['linen', 'white'],
    chinese: ['亚麻色', '白色'],
  },
  {
    category: 'red',
    key: '#800000',
    english: ['maroon', 'red'],
    chinese: ['褐红色', '红色'],
  },
  {
    category: 'green',
    key: '#66cdaa',
    english: ['mediumaquamarine', 'green'],
    chinese: ['中碧绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#0000cd',
    english: ['mediumblue', 'blue'],
    chinese: ['中蓝色', '蓝色'],
  },
  {
    category: 'purple',
    key: '#ba55d3',
    english: ['mediumorchid', 'purple'],
    chinese: ['中兰花紫色', '紫色'],
  },
  {
    category: 'purple',
    key: '#9370db',
    english: ['mediumpurple', 'purple'],
    chinese: ['中紫色', '紫色'],
  },
  {
    category: 'green',
    key: '#3cb371',
    english: ['mediumseagreen', 'green'],
    chinese: ['中海绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#7b68ee',
    english: ['mediumslateblue', 'blue'],
    chinese: ['中板岩蓝色', '蓝色'],
  },
  {
    category: 'green',
    key: '#00fa9a',
    english: ['mediumspringgreen', 'green'],
    chinese: ['中春绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#48d1cc',
    english: ['mediumturquoise', 'blue'],
    chinese: ['中绿宝石色', '蓝色'],
  },
  {
    category: 'red',
    key: '#c71585',
    english: ['mediumvioletred', 'red'],
    chinese: ['中紫罗兰红色', '红色'],
  },
  {
    category: 'blue',
    key: '#191970',
    english: ['midnightblue', 'blue'],
    chinese: ['午夜蓝色', '蓝色'],
  },
  {
    category: 'white',
    key: '#f5fffa',
    english: ['mintcream', 'white'],
    chinese: ['薄荷奶油色', '白色'],
  },
  {
    category: 'pink',
    key: '#ffe4e1',
    english: ['mistyrose', 'pink'],
    chinese: ['薄雾玫瑰色', '粉色'],
  },
  {
    category: 'orange',
    key: '#ffe4b5',
    english: ['moccasin', 'orange'],
    chinese: ['鹿皮色', '橙色'],
  },
  {
    category: 'orange',
    key: '#ffdead',
    english: ['navajowhite', 'orange'],
    chinese: ['纳瓦霍白色', '橙色'],
  },
  {
    category: 'white',
    key: '#fdf5e6',
    english: ['oldlace', 'white'],
    chinese: ['旧蕾丝色', '白色'],
  },
  {
    category: 'green',
    key: '#6b8e23',
    english: ['olivedrab', 'green'],
    chinese: ['橄榄褐色', '绿色'],
  },
  {
    category: 'orange',
    key: '#ffa500',
    english: ['orange'],
    chinese: ['橙色'],
  },
  {
    category: 'red',
    key: '#ff4500',
    english: ['orangered', 'red'],
    chinese: ['橙红色', '红色'],
  },
  {
    category: 'purple',
    key: '#da70d6',
    english: ['orchid', 'purple'],
    chinese: ['兰花紫色', '紫色'],
  },
  {
    category: 'yellow',
    key: '#eee8aa',
    english: ['palegoldenrod', 'yellow'],
    chinese: ['灰秋色', '黄色'],
  },
  {
    category: 'green',
    key: '#98fb98',
    english: ['palegreen', 'green'],
    chinese: ['苍绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#afeeee',
    english: ['paleturquoise', 'blue'],
    chinese: ['苍宝石色', '蓝色'],
  },
  {
    category: 'red',
    key: '#db7093',
    english: ['palevioletred', 'red'],
    chinese: ['苍紫罗兰红色', '红色'],
  },
  {
    category: 'yellow',
    key: '#ffefd5',
    english: ['papayawhip', 'yellow'],
    chinese: ['番木瓜色', '黄色'],
  },
  {
    category: 'orange',
    key: '#ffdab9',
    english: ['peachpuff', 'orange'],
    chinese: ['桃色', '橙色'],
  },
  {
    category: 'brown',
    key: '#cd853f',
    english: ['peru', 'brown'],
    chinese: ['秘鲁色', '棕色'],
  },
  {
    category: 'pink',
    key: '#ffc0cb',
    english: ['pink'],
    chinese: ['粉色', '粉红色'],
  },
  {
    category: 'purple',
    key: '#dda0dd',
    english: ['plum', 'purple'],
    chinese: ['李子色', '紫色'],
  },
  {
    category: 'blue',
    key: '#b0e0e6',
    english: ['powderblue', 'blue'],
    chinese: ['淡蓝色', '蓝色'],
  },
  {
    category: 'purple',
    key: '#663399',
    english: ['rebeccapurple', 'purple'],
    chinese: ['丽贝卡紫色', '紫色'],
  },
  {
    category: 'brown',
    key: '#bc8f8f',
    english: ['rosybrown', 'brown'],
    chinese: ['玫瑰棕色', '棕色'],
  },
  {
    category: 'blue',
    key: '#4169e1',
    english: ['royalblue', 'blue'],
    chinese: ['宝蓝色', '蓝色'],
  },
  {
    category: 'brown',
    key: '#8b4513',
    english: ['saddlebrown', 'brown'],
    chinese: ['马鞍棕色', '棕色'],
  },
  {
    category: 'red',
    key: '#fa8072',
    english: ['salmon', 'red'],
    chinese: ['鲑鱼红色', '红色'],
  },
  {
    category: 'brown',
    key: '#f4a460',
    english: ['sandybrown', 'brown'],
    chinese: ['沙棕色', '棕色'],
  },
  {
    category: 'green',
    key: '#2e8b57',
    english: ['seagreen', 'green'],
    chinese: ['海绿色', '绿色'],
  },
  {
    category: 'white',
    key: '#fff5ee',
    english: ['seashell', 'white'],
    chinese: ['贝壳白色', '白色'],
  },
  {
    category: 'brown',
    key: '#a0522d',
    english: ['sienna', 'brown'],
    chinese: ['黄土赭色', '棕色'],
  },
  {
    category: 'blue',
    key: '#87ceeb',
    english: ['skyblue', 'blue'],
    chinese: ['天蓝色', '蓝色'],
  },
  {
    category: 'blue',
    key: '#6a5acd',
    english: ['slateblue', 'blue'],
    chinese: ['板岩蓝色', '蓝色'],
  },
  {
    category: 'blue',
    key: '#708090',
    english: ['slategray', 'blue'],
    chinese: ['板岩灰色', '蓝色'],
  },
  {
    category: 'blue',
    key: '#708090',
    english: ['slategrey', 'blue'],
    chinese: ['板岩灰色', '蓝色'],
  },
  {
    category: 'white',
    key: '#fffafa',
    english: ['snow', 'white'],
    chinese: ['雪白色', '白色'],
  },
  {
    category: 'green',
    key: '#00ff7f',
    english: ['springgreen', 'green'],
    chinese: ['嫩绿色', '绿色'],
  },
  {
    category: 'blue',
    key: '#4682b4',
    english: ['steelblue', 'blue'],
    chinese: ['钢青色', '蓝色'],
  },
  {
    category: 'brown',
    key: '#d2b48c',
    english: ['tan', 'brown'],
    chinese: ['黄褐色', '棕色'],
  },
  {
    category: 'purple',
    key: '#d8bfd8',
    english: ['thistle', 'purple'],
    chinese: ['蓟色', '紫色'],
  },
  {
    category: 'red',
    key: '#ff6347',
    english: ['tomato', 'red'],
    chinese: ['番茄红色', '红色'],
  },
  {
    category: 'blue',
    key: '#40e0d0',
    english: ['turquoise', 'blue'],
    chinese: ['绿宝石色', '蓝色'],
  },
  {
    category: 'purple',
    key: '#ee82ee',
    english: ['violet', 'purple'],
    chinese: ['紫罗兰色', '紫色'],
  },
  {
    category: 'brown',
    key: '#f5deb3',
    english: ['wheat', 'brown'],
    chinese: ['小麦色', '棕色'],
  },
  {
    category: 'white',
    key: '#f5f5f5',
    english: ['whitesmoke', 'white'],
    chinese: ['烟白色', '白色'],
  },
  {
    category: 'green',
    key: '#9acd32',
    english: ['yellowgreen', 'green'],
    chinese: ['黄绿色', '绿色'],
  },
];

export const BASE_COLORS = [
  { category: 'red', key: '#ff0000', english: ['Red'], chinese: ['红色'] },
  {
    category: 'orange',
    key: '#ffa500',
    english: ['Orange'],
    chinese: ['橙色'],
  },
  { category: 'blue', key: '#0000ff', english: ['Blue'], chinese: ['蓝色'] },
  {
    category: 'yellow',
    key: '#ffff00',
    english: ['Yellow'],
    chinese: ['黄色'],
  },
  { category: 'green', key: '#008000', english: ['Green'], chinese: ['绿色'] },
  { category: 'cyan', key: '#00ffff', english: ['Cyan'], chinese: ['青色'] },
  {
    category: 'purple',
    key: '#800080',
    english: ['Purple'],
    chinese: ['紫色'],
  },
  { category: 'pink', key: '#FFC0CB', english: ['Pink'], chinese: ['粉色'] },
  { category: 'black', key: '#000000', english: ['Black'], chinese: ['黑色'] },
  { category: 'white', key: '#ffffff', english: ['White'], chinese: ['白色'] },
  { category: 'gray', key: '#808080', english: ['Gray'], chinese: ['灰色'] },
];
